### ISSUE TITLE
Inject is not a function

### ISSUE THREAD

**Issue by gregoryagu** [paulvanbladel/aurelia-auth#33]
After upgrading to the latest bits that were release today, I am getting the error "Inject is not a function." when aurelia-auth loads.

**Comment by paulvanbladel** [comment]
Thankq for  nticing.
And did you upgrade from very previous version?

**Comment by paulvanbladel** [comment]
I'll make an update later today.
cheers

**Comment by paulvanbladel** [comment]
Done.
v0.9.18

**Comment by gregoryagu** [comment]
Sorry for the delay on answering this, and thank you for updating.

However, I am still getting the same error message.  I just ran jspm update and all packages are up to day.  The version number of Aurelia-auth is 09.19.

    Loading plugin aurelia-auth.
Unhandled promise rejection Error: inject is not a function
	Error loading https://localhost:44300/jspm_packages/github/paulvanbladel/aurelia-auth@0.9.19.js
    at https://localhost:44300/jspm_packages/github/paulvanbladel/aurelia-auth@0.9.19/storage.js:97:15

**Comment by paulvanbladel** [comment]
Strange.
Can you check if versions of jspm components are same in plugin and your project.
E.g. aurelia-http-client.

**Comment by gregoryagu** [comment]
Yes, I did find some issues there.  Once I got everything on the same version, it started working correctly.  Thanks very much.

**Comment by paulvanbladel** [comment]
Happy you got it working.
